/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIKit.h>

@class MPVideoView, MovieTVHUDView, NPTVOutBackgroundView;

@interface MPVideoView : UIView  
- (id)initWithFrame:(struct CGRect)fp8;  
@end

@interface MPTVOutWindow : UIWindow
{
    NPTVOutBackgroundView *_backgroundView;
    MovieTVHUDView *_hudView;
    MPVideoView *_videoView;
}

- (id)initWithVideoView:(id)fp8;
- (void)dealloc;
- (BOOL)_canExistBeyondSuspension;
- (void)_playbackStateChanged:(id)fp8;

@end

