/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

//#import "NSObject.h"

@interface UIHardware : NSObject
{
}

+ (float)statusBarHeight;
+ (void)_setStatusBarHeight:(float)fp8;
+ (struct CGSize)mainScreenSize;
+ (struct CGRect)fullScreenApplicationContentRect;
+ (int)ringerState;
+ (int)deviceOrientation:(BOOL)fp8;
+ (BOOL)setSpeakerPhoneEnabled:(BOOL)fp8;
+ (BOOL)isTTYEnabled;
+ (struct CGSize)TVScreenSize;
+ (float)TVHorizontalPixelScale;
+ (BOOL)_TVOutStatus:(BOOL)fp8;
+ (BOOL)TVOutCapableAndPreferred;
+ (BOOL)TVOutCapable;
+ (void)TVOutResetPreferred;
+ (void)alertSheet:(id)fp8 buttonClicked:(int)fp12;
+ (void)accessoryAvailabilityChanged;
+ (id)deviceName;
+ (id)localizedDeviceName;
+ (void)_updateSystemSoundActiveStatus:(id)fp8;
+ (void)_registerForSystemSounds:(id)fp8;
+ (void)_unregisterForSystemSounds:(id)fp8;
+ (void)_playSystemSound:(unsigned long)fp8;

@end

